### ISSUE TITLE
Run tiny examples on travis

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#221]
@tskisner do you think it would be feasible to run the tiny examples on Travis and compare the results to a reference run?

If you agree this would be useful, I can start setting this up.

**Comment by jrmadsen** [comment]
All of the shell and many of the SLURM examples are already part of the nightly CTest/CDash testing located at http://jonathan-madsen.info/cdash/public/index.php?project=TOAST <http://jonathan-madsen.info/cdash/public/index.php?project=TOAST> until NERSC has a system setup to host it.  

A better alternative would be to configure TOAST with CMake and run: “ctest -DSTAGES=“Build;Test” -DTRIGGER=Test -S cdash/Stages.cmake -L UnitTest” to do the build and installation. The build log and the testing log are then pushed to the dashboard, which is far easier to view/navigate than the Travis logs. Also, this makes it easier to not only track which tests are failing (because each test is individually run), but be aware of build and configuration warnings.

**Comment by zonca** [comment]
thanks @jrmadsen, it looks like they are all failing on master. does that system run also on branches? can we check if a branch works before we merge a pull request?

**Comment by jrmadsen** [comment]
You can ignore those failing tests. This runs from my NERSC installation which currently has my ‘burst-buffer’ branch checked out. I set up a cron job that reinstalls the externals once a week and when Python was reinstalled, the externals didn’t also install TiMemory (which this branch uses) so all the Python tests failed because of this. I just noticed this today so the Nightly tests should be fine tonight.

The CDash doesn’t really trigger builds. Essentially, you just run that CTest command and it will record the results and push them to the dashboard. At NERSC, I do this via a cron job (that isn’t quite perfected as you can see) but I do this Travis-build-pushing-to-CDash for TiMemory and it works very well: http://jonathan-madsen.info/cdash/public/index.php?project=TiMemory&date=2018-02-23 <http://jonathan-madsen.info/cdash/public/index.php?project=TiMemory&date=2018-02-23>

**Comment by zonca** [comment]
The example tests are long to run, I'd rather have them run automatically on Travis, especially if I am doing just small code changes. Can you please point me to the scripts you are using to launch the examples? I think it would be useful to adapt them to also run on Travis.

**Comment by jrmadsen** [comment]
They have to be generated via: `cd examples; ./generate_shell.sh`

One can use the environment variables TYPES to control which ones are generated but by default it will generate all of them.

If you are configuring with CMake, the examples are automatically generated provided 
`-DGENERATE_EXAMPLES=ON` (which is the default). From the build directory:

- run the shell examples only: `ctest -L shell`
- run the unit tests only: `ctest -L UnitTest`
- run the unit tests and examples: `ctest -LE Slurm` or `ctest -L '(UnitTest|shell)'`

Useful CTest arguments: 

- `-O <filename>` : save the log to output file <filename>
- `-j N` : run N tests concurrently
- `-L XYZ` : regex include on the test labels
- `LE XYZ` : regex exclude on the test labels
- `-R XYZ` : regex include on the test names
- `-E XYZ` : regex exclude on the test names 
  - e.g `-E satellite` will exclude any tests with `satellite` in their name
- `--output-on-failure` : show the test output when a test fails
- `--rerun-failed` : only run the tests that failed the last time `ctest` was invoked
- `-N` : Disable actual execution of tests (useful to see which tests will be executed)
- `-V` : verbose output
- `-VV` : very verbose output
- `--debug` : `-VV` with extra internal CTest verbosity
- `--print-labels` : print available test lables. Currently these are:

  - CXX
  - Examples
  - Python
  - UnitTest
  - ground
  - ground_multisite
  - ground_simple
  - satellite
  - shell
  - tiny

**Comment by zonca** [comment]
Thanks, are you checking the outputs at all?

**Comment by jrmadsen** [comment]
No, currently the pass/fail relies on the exit code. There is a way to add a regex to trigger failures so, theoretically, one could parse the stdout and ensure it matches a known stdout. When it comes to the output files, we could theoretically use an MD5 checksum. I have implemented numerical comparisons with tolerances before in another code but it essentially requires having to create a separate python script or a utility like `numdiff`.

**Comment by tskisner** [comment]
@zonca, I believe that most of the time for travis to run is actually setting up toast and its dependencies.  There is one very long unit test (noise simulation) which is generating 100 MC's and looking at statistics. 
 This could be shortened.  Actually running the "tiny" tests would in fact be a very small increment of time compared to setting up the environment and running the unit tests.  

I actually really like having travis run our tests- it has caught many problems that would have only been discovered later.  Comparing the output data to a reference run would need some care to make sure we don't go over RAM limits loading maps, etc.  However, that is a nice idea.

**Comment by zonca** [comment]
ok, I am testing running at NSIDE 64 so maps are tiny, hosting at http://portal.nersc.gov/project/cmb/toast_data/ a pair of maps is only 200Kb compressed.

**Comment by zonca** [comment]
@tskisner ok I have the tiny example just for satellite now running on Travis, see https://github.com/hpc4cmb/toast/pull/228
I downsized the job quite a bit, nside 64, 1 hour observations, 8 nobs.
Do you think this is enough? or should I consider a larger test?

Once we decide the parameters I'll also run tests for the other pipelines.

**Comment by tskisner** [comment]
Thanks for this work @zonca.  It will be nice to have a more complete test run as part of travis, rather than the very contrived unit tests we currently have in src/python/tests/ops_madam.py

**Comment by zonca** [comment]
@keskitalo I am setting up automatic testing on Travis also for the ground examples, however they fail on my desktop, do I require external dependency to run the atmosphere simulations?

here the error message:

```bash
Simulating atmosphere                                                                                                               
0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Setting up atmosphere simulation                                                     
0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Instantiating the atmosphere for t = 0.0                                             
0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulating the atmosphere for t = 0.0
Exception occurred: "0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed."    
 ```

Full error message:
<details>

```bash
*** print_tb:
Exception occurred: "0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed."                                             *** print_tb:
  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1530, in <module>                                                main()
*** print_exception:                                                                                                                  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1530, in <module>
    main()                                                                                                                          *** print_exception:
Traceback (most recent call last):                                                                                                    File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1530, in <module>
    main()                                                                                                                            File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1463, in main
    simulate_atmosphere(args, comm, data, mc, mem_counter, totalname)                                                                 File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1100, in simulate_atmosphere
    atm.exec(data)                                                                                                                    File "/home/zonca/anaconda/envs/pysm2/lib/python3.6/site-packages/toast/tod/sim_det_atm.py", line 334, in exec
    raise RuntimeError(prefix + 'Simulation failed.')                                                                               RuntimeError: 0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed.
*** print_exc:                                                                                                                      Traceback (most recent call last):
  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1530, in <module>                                                main()
  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1463, in main                                                
    simulate_atmosphere(args, comm, data, mc, mem_counter, totalname)
  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1100, in simulate_atmosphere                                     atm.exec(data)
  File "/home/zonca/anaconda/envs/pysm2/lib/python3.6/site-packages/toast/tod/sim_det_atm.py", line 334, in exec
    raise RuntimeError(prefix + 'Simulation failed.')
RuntimeError: 0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed.                                           [264/9167]
*** print_exc:                                                                                                                      *** format_exc, first and last line:                                                                                                
Traceback (most recent call last):                                                                                                  RuntimeError: 0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed.                                                     
*** format_exception:                                                                                                               *** format_exc, first and last line:                                                                                                
Traceback (most recent call last):                                                                                                  RuntimeError: 0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed.                                                     
*** format_exception:
['Traceback (most recent call last):\n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1530, in <module>\n    main()\n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1463, in main\n    simulate_atmosphere(args, 
comm, data, mc, mem_counter, totalname)\n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1100, in simulate_atmosphere\n    atm.exec(data)\n', '  File "/home/zonca/anaconda/envs/pysm2/lib/python3.6/site-packages/toast/tod/sim_det_atm.py",
 line 334, in exec\n    raise RuntimeError(prefix + \'Simulation failed.\')\n', 'RuntimeError: 0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed.\n']
*** extract_tb:                                                                                                                     [<FrameSummary file /home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py, line 1530 in <module>>, <FrameSummary file /home/zonca/
anaconda/envs/pysm2/bin/toast_ground_sim.py, line 1463 in main>, <FrameSummary file /home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py, line 1100 in simulate_atmosphere>, <FrameSummary file /home/zonca/anaconda/envs/pysm2/lib/python3.6/site-packages/toast/tod
/sim_det_atm.py, line 334 in exec>]                                                                                                 *** format_tb:
['Traceback (most recent call last):\n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1530, in <module>\n    main()\n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1463, in main\n    simulate_atmosphere(args, 
comm, data, mc, mem_counter, totalname)\n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1100, in simulate_atmosphere\n    atm.exec(data)\n', '  File "/home/zonca/anaconda/envs/pysm2/lib/python3.6/site-packages/toast/tod/sim_det_atm.py",
 line 334, in exec\n    raise RuntimeError(prefix + \'Simulation failed.\')\n', 'RuntimeError: 0 : CES-ATACAMA-atacama_telescope-8x8deg-1-0 : Simulation failed.\n']
*** extract_tb:                                                                                                                     [<FrameSummary file /home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py, line 1530 in <module>>, <FrameSummary file /home/zonca/
anaconda/envs/pysm2/bin/toast_ground_sim.py, line 1463 in main>, <FrameSummary file /home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py, line 1100 in simulate_atmosphere>, <FrameSummary file /home/zonca/anaconda/envs/pysm2/lib/python3.6/site-packages/toast/tod
/sim_det_atm.py, line 334 in exec>]                                                                                                 *** format_tb:
['  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1530, in <module>\n    main()\n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1463, in main\n    simulate_atmosphere(args, comm, data, mc, mem_counter, totalname)\
n', '  File "/home/zonca/anaconda/envs/pysm2/bin/toast_ground_sim.py", line 1100, in simulate_atmosphere\n    atm.exec(data)\n', '  File "/home/zonca/anaconda/envs/pysm2/lib/python3.6/site-packages/toast/tod/sim_det_atm.py", line 334, in exec\n    raise RuntimeErr
or(prefix + \'Simulation failed.\')\n']
*** tb_lineno: 1530
```

</details>

**Comment by zonca** [comment]
I get the same kind of error on Travis, e.g. https://travis-ci.org/hpc4cmb/toast/jobs/356278651

**Comment by keskitalo** [comment]
@zonca that is unexpected. The external dependencies (Elemental and aatm) should be there because the initialization seems to work. It seems like the actual simulation part causes C++ to throw an exception. Any chance you are simply running out of memory?

**Comment by zonca** [comment]
I don't know, there is no error messages, but I don't think it is memory, `timemory` says 500MB and on my desktop I have 12GB. Anyway I can try make it smaller, how do I do that? I see you are setting `--start` but you are not setting `--stop`.

**Comment by keskitalo** [comment]
Thanks @tskisner. The ground example runs fine on my laptop and CDASH: http://jonathan-madsen.info/cdash/public/testDetails.php?test=17836&build=1134.

**Comment by zonca** [comment]
thanks @tskisner ,

@keskitalo what is the easiest way to disable atmosphere in the ground examples?

**Comment by keskitalo** [comment]
--skip_atmosphere

**Comment by zonca** [comment]
thanks @keskitalo,

it runs without atmosphere but madam cannot resolve the pixels, sigma and weights are both `NaN` for all channels:

```
        0 pixels solved                                                                                                             
   786432 pixels unsolved                                                                                                           
 Building RHS...                                                                                                                    
           0  : detector: fake_00A                                                                                                  
           0  : nna                                                                                                                 
           0  :                        NaN                       NaN                       NaN                       NaN            
           0  :                        NaN                       NaN                       NaN                       NaN            
           0  :                        NaN                       NaN                       NaN                       NaN            
           0  :                        NaN                       NaN                       NaN                       NaN            
                                                                                                                                    
  Madam fatal error: Masking bad baselines not implemented. Increase good_baseline_fraction  
```

do you know what could be wrong?

**Comment by keskitalo** [comment]
Do you have pyephem installed?

-R

**Comment by zonca** [comment]
yes

**Comment by keskitalo** [comment]
Is your branch in sync with master? There was an issue in optimized ground pointing simulation that I resolved last week.

-R

**Comment by zonca** [comment]
yes, it is updated

**Comment by zonca** [comment]
@keskitalo @tskisner what about just doing the satellite test for now? If you are ok with this I can update the pull request this way.

**Comment by keskitalo** [comment]
I don't we should give up on the ground examples.

**Comment by zonca** [comment]
ok @keskitalo, would you take a look at the logs and see if anything is suspect? https://travis-ci.org/hpc4cmb/toast/jobs/356852100

**Comment by keskitalo** [comment]
On line 5749: "Cannot find libmadam" https://travis-ci.org/hpc4cmb/toast/jobs/356852100#L5749

**Comment by zonca** [comment]
ok, thanks @keskitalo ,  I can finally reproduce on Travis the issue I had locally, where it appears to run fine but Madam gets all NaN, see:

https://travis-ci.org/hpc4cmb/toast/jobs/365223283#L6476

**Comment by keskitalo** [comment]
Looks like the noise weights in libmadam are NaN. Perhaps an issue with the simulated focal plane?

Why is majority of the log messages about downloading the data from the NERSC gateway?

**Comment by tskisner** [comment]
We could pipe that output to a log (or /dev/null), at least for the travis tests

**Comment by zonca** [comment]
@keskitalo I'll look into the weights,
could it be a problem to download data from NERSC gateway at each Travis test? should I host them on Github instead?

**Comment by zonca** [comment]
@tskisner sure I can pipe to /dev/null

**Comment by zonca** [comment]
@keskitalo the focalplane looks fine:

```
In [2]: pickle.load(open("fp_19.pkl", "rb"))
Out[2]: 
{'fake_00A': {'NET': 6e-05,
  'alpha': 1.0,
  'bandcenter_ghz': 25.0,
  'bandwidth_ghz': 6.3,
  'fknee': 0.05,
  'fmin': 1e-05,
  'fwhm': 10.0,
  'fwhm_deg': 0.16666666666666666,
  'index': 0,
  'quat': array([ 0.,  0.,  0.,  1.])},
 'fake_00B': {'NET': 6e-05,
  'alpha': 1.0,
  'bandcenter_ghz': 25.0,
  'bandwidth_ghz': 6.3,
  'fknee': 0.05,
  'fmin': 1e-05,
  'fwhm': 10.0,
  'fwhm_deg': 0.16666666666666666,
  'index': 1,
  'quat': array([ 0.        ,  0.        ,  0.70710678,  0.70710678])},
```

**Comment by zonca** [comment]
@keskitalo the focalplane looks fine, see above, if you have any other hint otherwise I'll print timelines across the script to find where NaNs first appear.

**Comment by keskitalo** [comment]
The timelines are most likely fine. The issue seems to be that Madam is being given NaNs as noise weights.

**Comment by zonca** [comment]
@keskitalo I printed `detweights` just before OpMadam, they are all 13888888.8888

**Comment by keskitalo** [comment]
@zonca it appears that Madam is being told to measure the noise weights from the noise PSDs:

```
 Initializing parameters
 Adjusting noise weights using noise spectra 
 Polarized detectors present:  Will produce polarization maps
 noise_weights_from_psd =  T
 radiometers =  T
 mode_detweight =            0
```

In the `radiometers = T` mode that means that Madam just gets the last bin of the noise PSD and uses it for the white noise level. Can you check if the noise PSDs are sensible?

**Comment by zonca** [comment]
@keskitalo do you mean saving some noise timelines and taking a PSD?

**Comment by keskitalo** [comment]
@zonca no. I mean looking at the PSD vectors that are being passed to Madam in OpMadam.

**Comment by zonca** [comment]
here is `psdfreqs` and `psdinfo`, in `psdinfo` there is an array of zeros but I don't know its meaning:

```
psdfreqs [  1.00000000e-09   1.40000000e-09   1.96000000e-09   2.74400000e-09                                                       
   3.84160000e-09   5.37824000e-09   7.52953600e-09   1.05413504e-08                                                                
   1.47578906e-08   2.06610468e-08   2.89254655e-08   4.04956517e-08                                                                
   5.66939124e-08   7.93714773e-08   1.11120068e-07   1.55568096e-07                                                                
   2.17795334e-07   3.04913467e-07   4.26878854e-07   5.97630396e-07                                                                
   8.36682554e-07   1.17135558e-06   1.63989781e-06   2.29585693e-06                                                                
   3.21419970e-06   4.49987958e-06   6.29983141e-06   8.81976398e-06                                                                
   1.23476696e-05   1.72867374e-05   2.42014324e-05   3.38820053e-05                                                                
   4.74348074e-05   6.64087304e-05   9.29722225e-05   1.30161112e-04                                                                
   1.82225556e-04   2.55115779e-04   3.57162090e-04   5.00026926e-04                                                                
   7.00037697e-04   9.80052775e-04   1.37207389e-03   1.92090344e-03                                                                
   2.68926482e-03   3.76497074e-03   5.27095904e-03   7.37934265e-03                                                                
   1.03310797e-02   1.44635116e-02   2.02489162e-02   2.83484827e-02                                                                
   3.96878758e-02   5.55630262e-02   7.77882366e-02   1.08903531e-01                                                                
   1.52464944e-01   2.13450921e-01   2.98831290e-01   4.18363806e-01                                                                
   5.85709328e-01   8.19993059e-01   1.14799028e+00   1.60718640e+00                                                                
   2.25006095e+00   3.15008534e+00   4.41011947e+00   6.17416726e+00                                                                
   8.64383416e+00   1.00000000e+01]        
```

```
psdinfo (array([ 13888888.88888889,  13888888.88888889,  13888888.88888889,                                                         
        13888888.88888889,  13888888.88888889,  13888888.88888889,                                                                  
        13888888.88888889,  13888888.88888889,  13888888.88888889,                                                                  
        13888888.88888889,  13888888.88888889,  13888888.88888889,                                                                  
        13888888.88888889,  13888888.88888889,  13888888.88888889,                                                                  
        13888888.88888889,  13888888.88888889,  13888888.88888889,                                                                  
        13888888.88888889]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 19, array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,                                                                                              
        0.,  0.,  0.,  0.,  0.,  0.]), 70, array([  1.00000000e-09,   1.40000000e-09,   1.96000000e-09,                             
         2.74400000e-09,   3.84160000e-09,   5.37824000e-09,                                                                        
         7.52953600e-09,   1.05413504e-08,   1.47578906e-08,                                                                        
         2.06610468e-08,   2.89254655e-08,   4.04956517e-08,                                                                        
         5.66939124e-08,   7.93714773e-08,   1.11120068e-07,                                                                        
         1.55568096e-07,   2.17795334e-07,   3.04913467e-07,                                                                        
         4.26878854e-07,   5.97630396e-07,   8.36682554e-07,                                                                        
         1.17135558e-06,   1.63989781e-06,   2.29585693e-06,                                                                        
         3.21419970e-06,   4.49987958e-06,   6.29983141e-06,                                                                        
         8.81976398e-06,   1.23476696e-05,   1.72867374e-05,                                                                        
         2.42014324e-05,   3.38820053e-05,   4.74348074e-05,                                                                        
         6.64087304e-05,   9.29722225e-05,   1.30161112e-04,                                                                        
         1.82225556e-04,   2.55115779e-04,   3.57162090e-04,                                                                        
         5.00026926e-04,   7.00037697e-04,   9.80052775e-04,                                                                        
         1.37207389e-03,   1.92090344e-03,   2.68926482e-03,                                                                        
         3.76497074e-03,   5.27095904e-03,   7.37934265e-03,                                                                        
         1.03310797e-02,   1.44635116e-02,   2.02489162e-02,                                                                        
         2.83484827e-02,   3.96878758e-02,   5.55630262e-02,                                                                        
         7.77882366e-02,   1.08903531e-01,   1.52464944e-01,                                                                        
         2.13450921e-01,   2.98831290e-01,   4.18363806e-01,                                                                        
         5.85709328e-01,   8.19993059e-01,   1.14799028e+00,                                                                        
         1.60718640e+00,   2.25006095e+00,   3.15008534e+00,                                                                        
         4.41011947e+00,   6.17416726e+00,   8.64383416e+00,                                                                        
         1.00000000e+01]), 1330, array([ 0.,  0.,  0., ...,  0.,  0.,  0.]))       
```

**Comment by keskitalo** [comment]
That last entry in `psdinfo` is a concatenated vector of the noise PSD values. For some reason the  PSDs are zero. The PSDs are extracted from the observation in https://github.com/hpc4cmb/toast/blob/master/src/python/map/madam.py#L468-L481

Either they are already zero or the `noise_scale` is zero.

**Comment by zonca** [comment]
`noise_scale` is zero.
I see the bug, `update_atmospheric_noise_weights` is not checking `args.skip_atmosphere` but only `args.weather`, so `noise_scale` instead of being set to 1 is set to zero, 45d1bc5 should fix it. Testing it.
