### ISSUE TITLE
error on test

### ISSUE THREAD

**Issue by chinoney** [hpc4cmb/toast#243]
I got the following error when I ran "echo "import toast.tests; toast.tests.run();" | OMP_NUM_THREADS=2 python3" at tostada1.
```
......
.............
Hit count written in toast_test_output/map_ground/madam_scansim/madam_hmap.fits
  test_scanmap (toast.tests.map_ground.MapGroundTest) ... OK (2.670s)
  test_binned (toast.tests.binned.BinnedTest) ... ERROR (2.430s)
  test_op_pysm_nosmooth (toast.tests.ops_sim_pysm.OpSimPySMTest) ... ERROR (0.097s)
  test_pysm_distrings (toast.tests.ops_sim_pysm.OpSimPySMTest) ... ERROR (0.043s)
  test_pysm_local_pix (toast.tests.ops_sim_pysm.OpSimPySMTest) ... ERROR (0.058s)
  test_op_pysm_smooth (toast.tests.ops_sim_pysm.OpSimPySMTestSmooth) ... ERROR (0.086s)
  test_smooth (toast.tests.smooth.LibSharpSmoothTest) ... OK (1.111s)

======================================================================
ERROR [0.708s]: test_phase (toast.tests.tod_satellite.TODSatelliteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/tests/tod_satellite.py", line 122, in test_phase
    hp.write_map(hitsfile, pdata, nest=False, dtype=np.int32)
  File "/usr/lib/python3/dist-packages/healpy/fitsfunc.py", line 153, in write_map
    tbhdu.header.update('PIXTYPE','HEALPIX','HEALPIX pixelisation')
  File "/usr/lib/python3/dist-packages/pyfits/header.py", line 1017, in update
    'value, and comment string.' % idx)
ValueError: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string.
....
.......
............
Ran 99 tests in 165.155s 

FAILED (errors=9)
/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/cache.py:96: RuntimeWarning: Cache object col2 has external references and will not be freed.
  warnings.warn("Cache object {} has external references and will not be freed.".format(k), RuntimeWarning)
/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/cache.py:96: RuntimeWarning: Cache object col3 has external references and will not be freed.
  warnings.warn("Cache object {} has external references and will not be freed.".format(k), RuntimeWarning)
/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/cache.py:96: RuntimeWarning: Cache object col1 has external references and will not be freed.
  warnings.warn("Cache object {} has external references and will not be freed.".format(k), RuntimeWarning)
/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/cache.py:96: RuntimeWarning: Cache object col4 has external references and will not be freed.
  warnings.warn("Cache object {} has external references and will not be freed.".format(k), RuntimeWarning)
/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/cache.py:96: RuntimeWarning: Cache object col0 has external references and will not be freed.
  warnings.warn("Cache object {} has external references and will not be freed.".format(k), RuntimeWarning)
/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/cache.py:96: RuntimeWarning: Cache object col5 has external references and will not be freed.
  warnings.warn("Cache object {} has external references and will not be freed.".format(k), RuntimeWarning)
/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/cache.py:121: RuntimeWarning: Cache object local_pixels has external references and will not be freed.
  warnings.warn("Cache object {} has external references and will not be freed.".format(k), RuntimeWarning)
Exception ignored in: <bound method OpSimPySM.__del__ of <toast.todmap.pysm_operator.OpSimPySM object at 0x7f8d8f33a080>>
Traceback (most recent call last):
  File "/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/todmap/pysm_operator.py", line 119, in __del__
    del self.pysm_sky
AttributeError: pysm_sky 
Exception ignored in: <bound method OpSimPySM.__del__ of <toast.todmap.pysm_operator.OpSimPySM object at 0x7f8d8f3f7550>>
Traceback (most recent call last):
  File "/opt/toast_2018-06-06/lib/python3.5/site-packages/toast/todmap/pysm_operator.py", line 119, in __del__
    del self.pysm_sky
AttributeError: pysm_sky 

```
I compiled the latest toast (e2de84716d84162295f5fea0000b9c9ec0172832) recently and tried to run. I haven't seen these errors before, e.g. around 2018-04-02 (6103c29c1d951af9b8cd1d27f3f5ec0d058dfedf).

**Comment by keskitalo** [comment]
@chinoney that is an incompatibility between `healpy` and `astropy.io.fits`. Are both updated to the latest versions?

**Comment by chinoney** [comment]
@keskitalo I used a script @tskisner provided in the repository (https://github.com/hpc4cmb/toast/blob/master/external/static/install_ubuntu_16.04.sh) to setup the environment @ tostada1. Probably the script need to be modified accordingly?

**Comment by keskitalo** [comment]
@chinoney Can you run this command on your system: `python3 -c 'import healpy; import astropy; print(healpy.__version__, astropy.__version__)'` and post the result?

**Comment by chinoney** [comment]
```
python3 -c 'import healpy; import astropy; print(healpy.__version__, astropy.__version__)' 
1.8.1 3.0.3
python3 -c 'import healpy; import astropy; print(healpy.__file__, astropy.__file__)' 
/usr/lib/python3/dist-packages/healpy/__init__.py /opt/toast_2018-06-06/lib/python3.5/site-packages/astropy-3.0.3-py3.5-linux-x86_64.egg/astropy/__init__.py
```
It seems healpy which is installed by the script is NOT loaded correctly even I set

```
toast(){
    pref=/opt/toast_2018-06-06
    export PATH=${pref}/bin:${PATH}
    export LD_LIBRARY_PATH=${pref}/lib:${LD_LIBRARY_PATH}
    export PYTHONPATH=${pref}/lib/python3.5/site-packages:${PYTHONPATH}
}
toast
```
Then I realized the installation w/ the script seems failed. I'll check that, but I'm not sure why failed. It sometimes fails to me.

**Comment by chinoney** [comment]
If healpy was installed successfully, it's "1.11.0"

**Comment by tskisner** [comment]
I can go re-check the dependency installation script in a 16.04 docker image (or on tostada) if that is helpful...

**Comment by chinoney** [comment]
Yes, this has solved the problem. I understand I should check whether the necessary installation by the script has succeeded or not.
