### ISSUE TITLE
test ops_sim_pysm failing when libsharp is used

### ISSUE THREAD

**Issue by ickc** [hpc4cmb/toast#308]
# Description

This error is known to not easy to reproduce. For example it cannot be reproduced on @keskitalo's Macbook Pro. @tskisner also see similar error on Travis CI and current CI has this case disabled.

The failing test case is `ops_sim_pysm`. Note that only when MPI is used, `libsharp` is used. As below shows `ops_sim_pysm` only fail when MPI is used. i.e. the problem is originate from `libsharp`. Also, running the test from `libsharp` itself is passing.

We have an idea to further test this and will report when that's done.

```python
from mpi4py import MPI
```

```python
from toast.tests import ops_sim_pysm
```

# Environment

```python
from toast import Environment
```

```python
Environment.get()
```

    <toast.Environment
      Source code version = 2.3.1.dev1444
      Logging level = INFO
      Handling enabled for 0 signals:
      Max threads = 20
      MPI build enabled
      MPI runtime enabled
    >

```python
! uname -r
```

    5.3.7-arch1-1-ARCH

```python
! gcc --version
```

    gcc (GCC) 9.2.0
    Copyright (C) 2019 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    

```python
! /opt/mpich/bin/mpiexec --version
```

    HYDRA build details:
        Version:                                 3.3.1
        Release Date:                            Wed Jun  5 14:57:33 CDT 2019
        CC:                              gcc    
        CXX:                             g++    
        F77:                             gfortran   
        F90:                             gfortran   
        Configure options:                       '--disable-option-checking' '--prefix=/opt/mpich' '--enable-error-checking=runtime' '--enable-error-messages=all' 'CC=gcc' 'CXX=g++' 'FC=gfortran' 'MPICHLIB_CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' 'MPICHLIB_CPPFLAGS=-D_FORTIFY_SOURCE=2' 'MPICHLIB_CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' 'MPICHLIB_FFLAGS=' '--cache-file=/dev/null' '--srcdir=../../../../src/pm/hydra' 'CFLAGS= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= -D_FORTIFY_SOURCE=2 -I/home/kolen/.cache/yay/mpich/src/mpich-3.3.1/build/src/mpl/include -I/home/kolen/.cache/yay/mpich/src/mpich-3.3.1/src/mpl/include -I/home/kolen/.cache/yay/mpich/src/mpich-3.3.1/src/openpa/src -I/home/kolen/.cache/yay/mpich/src/mpich-3.3.1/build/src/openpa/src -D_REENTRANT -I/home/kolen/.cache/yay/mpich/src/mpich-3.3.1/build/src/mpi/romio/include' 'MPLLIBNAME=mpl'
        Process Manager:                         pmi
        Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
        Topology libraries available:            hwloc
        Resource management kernels available:   user slurm ll lsf sge pbs cobalt
        Checkpointing libraries available:       
        Demux engines available:                 poll select

pysm version

```python
! cd /scratch/local/toast-gnu/git/pysm && git rev-parse --short HEAD
```

    09d7fb3

libsharp version

```python
! cd /scratch/local/toast-gnu/git/libsharp && git rev-parse --short HEAD
```

    cc4753f

# `libsharp` test ok

```python
! cd /scratch/local/toast-gnu/git/libsharp && make test
```

    using configuration 'auto'
    
    +---------------+
    | sharp_acctest |
    +---------------+
    
    Supported vector length: 4
    OpenMP active: max. 20 threads.
    MPI active, but running with 1 task only.
    
    Checking signs and scales.
    Passed.
    
    Testing map analysis accuracy.
    lmax: 127, mmax: 127
    Gauss-Legendre grid, nlat=128, nlon=256
    Passed.
    
    
    +------------+
    | sharp_test |
    +------------+
    
    Supported vector length: 4
    OpenMP active: max. 20 threads.
    MPI active, but running with 1 task only.
    
    Testing map analysis accuracy.
    spin=0, ntrans=1
    lmax: 2048, mmax: 2048
    HEALPix grid, nside=1024
    Best of 10 runs
    wall time for alm2map: 0.107592s
    Performance: 248.564902GFLOPs/s
    wall time for map2alm: 0.100608s
    Performance: 262.452313GFLOPs/s
    component 0: rms 1.036580e-03, maxerr 7.764271e-02
    
    Memory high water mark: 181.23 MB
    Memory overhead: 53.19 MB (29.35% of working set)
    (null)       healpix     0 4 20   1   2048   2048   1024     -1  1 1.08e-01  248.56 1.01e-01  262.45    181.23  29.35 1.04e-03 7.76e-02
    
    +------------+
    | sharp_test |
    +------------+
    
    Supported vector length: 4
    OpenMP active: max. 20 threads.
    MPI active, but running with 1 task only.
    
    Testing map analysis accuracy.
    spin=2, ntrans=1
    lmax: 2047, mmax: 2047
    Fejer1 grid, nlat=4095, nlon=4096
    Best of 4 runs
    wall time for alm2map: 0.322474s
    Performance: 274.944917GFLOPs/s
    wall time for map2alm: 0.272721s
    Performance: 325.103591GFLOPs/s
    component 0: rms 8.126880e-13, maxerr 4.414047e-11
    component 1: rms 8.115839e-13, maxerr 4.507140e-11
    
    Memory high water mark: 392.04 MB
    Memory overhead: 72.07 MB (18.38% of working set)
    (null)       fejer1      2 4 20   1   2047   2047   4095   4096  1 3.22e-01  274.94 2.73e-01  325.10    392.04  18.38 8.13e-13 4.51e-11
    
    +------------+
    | sharp_test |
    +------------+
    
    Supported vector length: 4
    OpenMP active: max. 20 threads.
    MPI active, but running with 1 task only.
    
    Testing map analysis accuracy.
    spin=0, ntrans=2
    lmax: 2047, mmax: 2047
    Gauss-Legendre grid, nlat=2048, nlon=4096
    Best of 13 runs
    wall time for alm2map: 0.075624s
    Performance: 251.711891GFLOPs/s
    wall time for map2alm: 0.068949s
    Performance: 276.082177GFLOPs/s
    component 0: rms 1.318647e-12, maxerr 8.594176e-11
    component 1: rms 1.396678e-12, maxerr 9.183873e-11
    
    Memory high water mark: 255.74 MB
    Memory overhead: 63.71 MB (24.91% of working set)
    (null)       gauss       0 4 20   1   2047   2047   2048   4096  2 7.56e-02  251.71 6.89e-02  276.08    255.74  24.91 1.40e-12 9.18e-11

# Test failure

The same error is shown by either running it in Python or command line as below

## Command line

When MPI is not used, `libsharp` is not called, and it's fine.

```python
! TOAST_MPI_DISABLE=1 python -c "from toast.tests import run; run('ops_sim_pysm')"
```

    
    test_op_pysm_nosmooth (toast.tests.ops_sim_pysm.OpSimPySMTest) ... TOAST INFO: PySM Operator:  5.01 seconds (1 calls)
    ok 
    test_pysm_local_pix (toast.tests.ops_sim_pysm.OpSimPySMTest) ... ok 
    test_pysm_ring_distribution (toast.tests.ops_sim_pysm.OpSimPySMTest) ... ok 
    test_op_pysm_smooth (toast.tests.ops_sim_pysm.OpSimPySMTestSmooth) ... TOAST INFO: PySM Operator:  0.65 seconds (1 calls)
    ok 
    
    ----------------------------------------------------------------------
    Ran 4 tests in 8.509s
    
    OK

When MPI is used, `libsharp` is called, and it's failing. Note that `x` is the computed one and `y` is the expected one.

```python
! python -c "from toast.tests import run; run('ops_sim_pysm')"
```

    
    test_op_pysm_nosmooth (toast.tests.ops_sim_pysm.OpSimPySMTest) ... TOAST INFO: PySM Operator:  4.96 seconds (1 calls)
    [0]ok 
    test_pysm_local_pix (toast.tests.ops_sim_pysm.OpSimPySMTest) ... [0]ok 
    test_pysm_ring_distribution (toast.tests.ops_sim_pysm.OpSimPySMTest) ... [0]ok 
    test_op_pysm_smooth (toast.tests.ops_sim_pysm.OpSimPySMTestSmooth) ... TOAST INFO: PySM Operator:  0.44 seconds (1 calls)
    [0]fail 
    
    [0] ======================================================================
    [0] FAIL: test_op_pysm_smooth (toast.tests.ops_sim_pysm.OpSimPySMTestSmooth)
    [0] ----------------------------------------------------------------------
    [0] Traceback (most recent call last):
      File "/scratch/local/toast-gnu/compile/lib/python3.7/site-packages/toast/tests/ops_sim_pysm.py", line 251, in test_op_pysm_smooth
        rescanned_tod[:3], expected, decimal=0 if self.comm is None else 1
      File "/scratch/local/toast-gnu/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1029, in assert_array_almost_equal
        precision=decimal)
      File "/scratch/local/toast-gnu/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 841, in assert_array_compare
        raise AssertionError(msg)
    AssertionError: 
    Arrays are not almost equal to 1 decimals
    
    Mismatch: 100%
    Max absolute difference: 43467.58239987
    Max relative difference: 443.37112644
     x: array([-24558.8, -38499.3, -43369.5])
     y: array([99.1, 97.5, 98. ])
    
    ----------------------------------------------------------------------
    Ran 4 tests in 8.329s
    
    [0] FAILED (failures=1)

## Python

When MPI is not used, `libsharp` is not called, and it's fine.

```python
test = ops_sim_pysm.OpSimPySMTestSmooth()
```

```python
test.comm = None
```

```python
test.setUp()
```

```python
test.test_op_pysm_smooth()
```

When MPI is used, `libsharp` is called, and it's failing. Note that `x` is the computed one and `y` is the expected one.

```python
test.comm = MPI.COMM_WORLD
```

```python
test.setUp()
```

```python
test.test_op_pysm_smooth()
```

    ---------------------------------------------------------------------------

    AssertionError                            Traceback (most recent call last)

    <ipython-input-19-e840eb4169f1> in <module>
    ----> 1 test.test_op_pysm_smooth()
    

    /scratch/local/toast-gnu/compile/lib/python3.7/site-packages/toast/tests/ops_sim_pysm.py in test_op_pysm_smooth(self)
        249         if rank == 0:
        250             np.testing.assert_array_almost_equal(
    --> 251                 rescanned_tod[:3], expected, decimal=0 if self.comm is None else 1
        252             )
        253         return

    /scratch/local/toast-gnu/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py in assert_array_almost_equal(x, y, decimal, err_msg, verbose)
       1027     assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
       1028              header=('Arrays are not almost equal to %d decimals' % decimal),
    -> 1029              precision=decimal)
       1030 
       1031 

    /scratch/local/toast-gnu/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
        839                                 verbose=verbose, header=header,
        840                                 names=('x', 'y'), precision=precision)
    --> 841             raise AssertionError(msg)
        842     except ValueError:
        843         import traceback

    AssertionError: 
    Arrays are not almost equal to 1 decimals
    
    Mismatch: 100%
    Max absolute difference: 16968.04553464
    Max relative difference: 173.07476162
     x: array([-12861.8, -16573.3, -16870. ])
     y: array([99.1, 97.5, 98. ])

**Comment by ickc** [comment]
I tried to compile libsharp with `-fsplit-stack` option and it has the same test failure. But I'm not sure if that's the idea @tskisner has in mind.

**Comment by ickc** [comment]
ping @zonca as he knows more about libsharp.

**Comment by zonca** [comment]
I have no idea what is going on, maybe NSIDE is really low and transform is badly defined?
I can take care of debugging, this, it is going to take some time though.
But if you have any more tests or ideas on how to debug this, please go ahead!

**Comment by mreineck** [comment]
I just stumbled over this by accident ...

Do you suspect the problem is in `libsharp` itself? If so, can you describe how it is called (i.e. how many MPI tasks, which rings on which task, which m on which task etc.)?
It's possible that I have overlooked some corner case where an MPI task does not get any m value or any ring pair, and that this in turns leads to garbage results.
On the other hand, in such a situation I'd rather expect a segmentation fault instead of just a bad result...

**Comment by ickc** [comment]
The result most probably is in `libsharp` itself. The problem is that it is hard to reproduce. It is very stateful in the sense that a change in the environment could make it work or break. We know that it is failing on one of my computer, on Travis, on yours, but not on other people's computers including Reijo's and Ted's, and on NERSC.

**Comment by mreineck** [comment]
OK, but if I knew what the actual call to the libsharp library looks like, I could setup a pure C testing environment (using valgrind and other tools), which is much easier to handle than debugging something wrapped in Python.
Of course it may not fail then, but if there is some dodgy memory access going on, valgrind will still detect it.

**Comment by tskisner** [comment]
Hello @mreineck and @zonca.  TOAST does not call libsharp itself.  Instead, it calls this PySM function:

https://github.com/hpc4cmb/toast/blob/dbd8fa679e34a7a703a8cb2ebb4830e5792769be/src/toast/todmap/sim_det_pysm.py#L202

Which in turn calls this in the MPI case:

https://github.com/healpy/pysm/blob/8a6affeeee55a889fabd8d518efcccea5f335786/pysm/models/template.py#L121

Which uses libsharp:

https://github.com/healpy/pysm/blob/8a6affeeee55a889fabd8d518efcccea5f335786/pysm/mpi.py#L119

One way to isolate this would be to find a simulation job and machine where we see the problem, and then dump out the information being passed to libsharp in that last link.
