### ISSUE TITLE
Issue with importing pysm

### ISSUE THREAD

**Issue by Ankurdev-astro** [hpc4cmb/toast#484]
Hi,
I am running _toast_ground_sim.py_ with _[--pysm-model ]_ and  _[--pysm-apply-beam]_ parameters on toast v2.3.12 . I have _pysm3_ v3.3.2.dev46+g5c339f0 installed. 
The pipeline throws an error : _RuntimeError: PySM not available_ .

Should I have _**pysm**_ installed, instead of _**pysm3**_ ? 

```
! toast_ground_sim.py @toast_ground_sim.par
<toast.Environment
  Source code version = 8dbc082
  Logging level = INFO
  Handling enabled for 0 signals:
  Max threads = 128
>
```
...
```
TOAST INFO: Pointing generation:  20.44 seconds (1 calls)
Traceback (most recent call last):
  File "/users/adev/anaconda3/envs/toast-test/bin/toast_ground_sim.py", line 631, in <module>
    main()
  File "/users/adev/anaconda3/envs/toast-test/bin/toast_ground_sim.py", line 470, in main
    signalname = pipeline_tools.simulate_sky_signal(
  File "/users/adev/anaconda3/envs/toast-test/lib/python3.8/site-packages/toast/timing.py", line 43, in df
    return f(*args, **kwargs)
  File "/users/adev/anaconda3/envs/toast-test/lib/python3.8/site-packages/toast/pipeline_tools/sky_signal.py", line 404, in simulate_sky_signal
    op_sim_pysm = OpSimPySM(
  File "/users/adev/anaconda3/envs/toast-test/lib/python3.8/site-packages/toast/timing.py", line 43, in df
    return f(*args, **kwargs)
  File "/users/adev/anaconda3/envs/toast-test/lib/python3.8/site-packages/toast/todmap/sim_det_pysm.py", line 121, in __init__
    raise RuntimeError("PySM not available")
RuntimeError: PySM not available
```

![toast_pysm_issue](https://user-images.githubusercontent.com/34693706/134693729-343a88d1-f8f1-40e5-8805-b100fb40697e.png)

**In addition:** 
https://github.com/hpc4cmb/toast/blob/e24107daa99797a314d0e579a6351ee1f3b04aa0/src/toast/todmap/pysm.py

The pysm.py file imports 
```
try:
    import pysm
    import pysm.units as u
```

But class _PySMSky(object)_: documents _" Requires PySM 3 "_

**Should pysm.py import pysm3 instead?**

**Comment by zonca** [comment]
Yes, correct, you should change the import statement. We haven't used this functionality in a while so I'm not sure if it is still working properly. Please double check the outputs.

**Comment by tskisner** [comment]
In main branch we no longer run pysm on the fly.  Instead we support scanning from per-detector maps.
