### ISSUE TITLE
Failing conviqt test

### ISSUE THREAD

**Issue by gabrielecoppi** [hpc4cmb/toast#606]
I am running toast3 installed using `pip install --pre --upgrade toast3`. I have set-up a conda environment with all the dependencies (including _madam_ and _conviqt_) and I am failing the _conviqt_ tests. This is the message that I am getting:

```
Proc 0: Traceback (most recent call last):
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/tests/ops_sim_tod_conviqt.py", line 492, in test_sim_TEB_conviqt
    sim_conviqt.apply(data)
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/timing.py", line 107, in df
    return f(*args, **kwargs)
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/ops/operator.py", line 115, in apply
    self.exec(data, detectors, use_accel=use_accel, **kwargs)
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/timing.py", line 107, in df
    return f(*args, **kwargs)
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/ops/operator.py", line 52, in exec
    self._exec(
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/timing.py", line 81, in df
    return f(*args, **kwargs)
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/ops/conviqt.py", line 264, in _exec
    all_detectors = self._get_all_detectors(data, detectors)
Proc 0:   File "/home/gabriele/miniforge3/envs/cmb/lib/python3.10/site-packages/toast/ops/conviqt.py", line 317, in _get_all_detectors
    exists = obs.detdata.ensure(
Proc 0: TypeError: DetDataManager.ensure() got an unexpected keyword argument 'units'
```

Looking at the line [here](https://github.com/hpc4cmb/toast/blob/70effe3c18b0275c819be4f0b17211b2352d2ed8/src/toast/ops/conviqt.py#L317) and comparing with the _ensure_ definition [here](https://github.com/hpc4cmb/toast/blob/70effe3c18b0275c819be4f0b17211b2352d2ed8/src/toast/observation_data.py#L612), it seems that the _units_ keyword needs to be changed to _create_units_

**Comment by tskisner** [comment]
Thanks for catching this typo!  I'll double check there are no other cases and also see why this failure was not picked up by the CI tests.

**Comment by gabrielecoppi** [comment]
No problem. This was the only test failed based on my configuration.

**Comment by giuspugl** [comment]
I can reproduce the `TypeError`  both in perlmutter and in Cori . thanks @gabrielecoppi  !

**Comment by keskitalo** [comment]
PR #610 fixes the issue. Do we install libconviqt in our CI?

**Comment by tskisner** [comment]
Hi @keskitalo , in principle the libconviqt unit test should run when we run the MPI tests within out docker container, for example:  https://github.com/hpc4cmb/toast/blob/ddae67de4154067d2317999f6cf6c31dd48ae047/.github/workflows/test.yml#L30

I should check that those are working...

**Comment by tskisner** [comment]
Looks like something is not catching the failing unit tests.  I am leaving this open until it is addressed.
